### ISSUE TITLE
Tests fail in release profile

### ISSUE THREAD

**Issue by michaelsproul** [orium/archery#28]
Running the tests with release currently fails, i.e.

```
cargo test --release
```

Part of the reason is that the compile-fail tests hardcode `debug` into the path here:

https://github.com/orium/archery/blob/11bdf0a4a8d298e1e58ab19908a81f66ab661da2/tests/tests.rs#L51

However even when I fixed that path I still got weird failures. Perhaps we could slap a `#![cfg(debug_assertions)]` on the compile-fail tests?

**Comment by orium** [comment]
I think I know the "weird failures" you mentioned. I had them before. I'll try to take a look at that this week.
